repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks # Enables fast path
      rev: v4.5.0 # This is ignored for fast path detection
      hooks:
          - id: check-case-conflict
    - repo: local
      hooks:
          - id: content
            name: Content
            language: system
            entry: prettier --check
            files:
                glob:
                    - "content/**/*.md"
          - id: authors
            name: Author
            language: system
            entry: prettier --check
            files:
                glob:
                    - "data/authors/**/*.yaml"
                    - ".pre-commit-config.yaml"
          - id: github
            name: GitHub
            language: system
            entry: "prettier --check"
            files:
                glob:
                    - ".github/**/*.yml"
          - id: config
            name: Config
            language: system
            entry: tombi format  --check --offline
            files:
                glob:
                    - "config/**/*.toml"
